<html>
<link rel="stylesheet" type="text/css" href="http://localhost/quiz_project_final_final/aboutus.css">  <section id="contact">
	<div class="sectionheader">	<h1>ABOUT US!</h1></div>
	<article>
		<hr>
	<p> WE ARE THE STUDENTS OF THE JNTUA COLLEGE OF ENGINEEERING......<br>PULIVENDHULA.<br>..<br>...<br>
	<PRE>
		<hr>
          CONTACT NO:+91 943791XXXX
          EMIAL:JNTUCEP158218@GMIAL.COM
          ADDRESS:KADAPA,A.P,INDIA........

      </PRE>
    </p>
		</article></section></html>